name: 'Kingly paragraph media'
type: 'Site'
description: Configures a Kingly media paragraph.
recipes:
  - core/recipes/audio_media_type
  - core/recipes/document_media_type
  - core/recipes/image_media_type
  - core/recipes/local_video_media_type
  - core/recipes/remote_video_media_type

install:
  - paragraphs
  - layout_paragraphs
  - pathauto
  - media_library
  - focal_point
  - responsive_image
  - svg_image

config:
  strict: false
